
CREATE SEQUENCE IF NOT EXISTS SQ_PRODUTO
    START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS TB_PRODUTO (
    id BIGINT NOT NULL DEFAULT nextval('SQ_PRODUTO'),
    nome VARCHAR(100) NOT NULL,
    codigo VARCHAR(20) NOT NULL,
    preco DECIMAL(10,2),
    estoque INTEGER,
    em_estoque BOOLEAN DEFAULT TRUE,

    CONSTRAINT PK_ID_PRODUTO PRIMARY KEY (ID),
    CONSTRAINT UK_CODIGO_PRODUTO UNIQUE (CODIGO)
);