
CREATE SEQUENCE IF NOT EXISTS SQ_CLIENTE
    START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS TB_CLIENTE (
    id BIGINT NOT NULL DEFAULT nextval('SQ_CLIENTE'),
    nome VARCHAR(50) NOT NULL,
    codigo VARCHAR(20) NOT NULL,

    CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID),
    CONSTRAINT UK_CODIGO_CLIENTE UNIQUE (CODIGO)
);